### ISSUE TITLE
PixiGraphics (Rectangle, Circle,...) cannot inherit to their children

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#12]
Today I tested (learned) the functionality of the react hooks (like your position update) and the pass parameters using props. And I found something unexpected.

If I nest a htmlContainer or a rectangle into a sprite like in your example in https://mcastiello.github.io/pixi-reactive/#/index/components/pixihtmlcontainer/ :

```
  const [trackSize, setTrackSize] = useState(0);
  const setSpritePosition = useCallback((position) => (position + 4) % trackSize, [trackSize]);
  const [position, update] = useReducer(setSpritePosition, 0);

  return (
            <PixiSprite texture={'ship'} x={position} y={props.y} alignY={0.5} >
                <PixiHtmlContainer >
                    <Balloon >{'Spaceship #1'}</Balloon>
                </PixiHtmlContainer>
            </PixiSprite>
)
```
everything works as expected.

If I nest a sprite into a rectangle,
```
      <PixiGraphics>
        <Rectangle x={position} y={20} width={200} height={200} borderRadius={10}>
          <PixiSprite texture={'ship'} x={300} y={0} alignY={0.5} >
            <FillStyle color={0x444444} alpha={0.75} />
          </PixiSprite>
      </PixiGraphics>
```
the only thing that updated by the props and the position-hook is the rectangle by itself. The PixiSprite and all his childrens stay untouched.

So I nest a htmlElement into a rectangle... and fascinating things happened.
```
      <PixiGraphics>
        <Rectangle x={position} y={props.y} width={200} height={300} borderRadius={10}>
        <PixiHtmlContainer >
            <Balloon >{'Spaceship #1'}</Balloon>
          </PixiHtmlContainer>
          <PixiSprite texture={'ship'} x={300} y={0} alignY={0.5} >
            <FillStyle color={0x444444} alpha={0.75} />
          </PixiSprite>
        </Rectangle>
      </PixiGraphics>
```
the htmlContainer walks in the inverted direction of the rectangle, we can see that something is processed by the hooks. The props affected only the rectangle. And if I delete the Sprite in this construction, the other two elements will be erased. But if the Rectangle stays alone all works fine.

I tried that also with the Circle and the same effects happened. Probably all PixiGraphics are affected.

**Comment by mcastiello** [comment]
That is because rectangles and any other shape or style are not display objects, they are logical objects that can only make sense within the `PixiGraphics` element.
You should not add display objects as children of a shape. You can add them as children of the PixiGraphic element if you want

**Comment by Sylraka** [comment]
This may be. Either way, something is wrong with the update events. 
Because pixi-reactive doesn't work in codesandbox, i implement a little example you can clone from https://github.com/Sylraka/pixi-reactive-examples . You can try it yourself. 

The boardGlobal set the props for primitive-card one and two. The first time the scene rendered the props will transfer correctly. But if the props are changed in runtime, the rerendering will not triggered from the onUpdate lifecycle. 

Furthermore the onClick-methods from the primitive cards are not triggering by clicking and I have no idea why. Instead of this they trigger by the first render of the site. The only working onClick-method is from boardGlobal, maybe because it has his own PixiCanvas?
Can you do something about it?

**Comment by mcastiello** [comment]
The click is not triggering because you are calling the function instead of passing a callback reference.
Try this:
```jsx
      <PixiSprite texture={'ship'} alignY={0.5} alignX={0.5}
                cursor={CursorType.Help}
                buttonMode={true} interactive={true} onClick={() => printProps(this.props.cardProps)} />
```

I think it is also worth noting that this is not how react works.
```js
const clicktest = () => {
    console.log("cardProps 1 and 2 changed!");
    cardProps1.text = 'neuer text';
    cardProps1.x = 0;

    cardProps2.text = 'neuer text';
    cardProps2.x = 0;
}
```
You are updating the content of an object, but you are passing the object by reference to the props. This means that React do not see any changes in the reference, hence it does not update the element.
You may want to use a reducer function instead of an external callback, and be mindful of generating a new object instead of modifying the previous state.
I hope this helps.

**Comment by Sylraka** [comment]
To pass a callback reference works for the PixiSprite-element, here it works yet :)
Sorry, now I see that the problem "call a function with values" is a typical react-beginner-problem.
But not all Elements accept that onClick-method. The PixiGraphics-element still won't trigger as well as the PixiContainer-element. According to your documentation they should be able to do that.

And as for the props: How can I generate a new object in runtime and hand over it to the props? For that scenario I lack the know-how about the syntax :_:

**Comment by mcastiello** [comment]
When it comes to the PixiContainer, that is something you need to ask the Pixi devs, I can't remember now, but you may need to define a hit area to make it clickable. The PixiGraphics is basically the same of a Sprite, so there's no reason why it should not trigger a click. Make sure you made it interactive and set buttonMode to true.

About React, you may want to have a look at the `useReducer` hook: https://reactjs.org/docs/hooks-reference.html#usereducer

**Comment by Sylraka** [comment]
I updated the example in https://github.com/Sylraka/pixi-reactive-examples .
Like you say the update lifecycles are working fine with an integrated hook.

The PixiGraphics element is clickable after setting interactive and buttonMode (shame on me), only the CursorType is not displayed correctly. 
The PixiContainer isn't clickable with hitArea either. I think the hitArea don't create any clickable area. If I add some hitArea to the working Pixi-Sprite (see primitive-card1), it lost his clickability.

**Comment by mcastiello** [comment]
The prop to set the cursor type is `cursor` not `CursorType`
