### ISSUE TITLE
Texture cannot scale correctly (after page reload)

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#13]
**Action:**
Add some width and height to a PixiSprite

**Excepted Behavior:**
Sprite is scaled to the specified height and width. This should be presented in the same way at all times. 

**Found Behavior:**
After adding the width and height the Sprite is displayed correctly. After a page reload (and every load from that point) the height scale will be ignored and the width scale goes in the infinity. That happens regardless of the place the PixiSprite is loaded and the format of the texture.

**Comment by mcastiello** [comment]
please, provide an example of your code

**Comment by mcastiello** [comment]
Actually, don't mind, I think I managed to reproduce it

**Comment by mcastiello** [comment]
This latest update should fix the issue: https://github.com/mcastiello/pixi-reactive/commit/65992b01bed4cc31bc4db070dd481f0dd9d1e0aa
The published version is `1.3.22`
