### ISSUE TITLE
PixiHTMLContainer has his own PointerContext-Coordinates

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#15]
**Actions:**
- Add a PointerContext to the canvas 
- Add a PixiHTMLContainer to the canvas 

**Expected behaviour**
The PointerContext holds the coordinates of the cursor inside the canvas (see image). 
![Screenshot 2022-01-30 at 16 11 52](https://user-images.githubusercontent.com/27310921/151706452-1d1c1349-fca8-4355-860f-afa5d024ca9e.png)
It should hold this coordinates over all elements inside the canvas.

**Found behaviour**
The PointerContext coordinates set a new coordinate system if hover over a PixiHTMLContainer (see image).
![Screenshot 2022-01-30 at 16 12 10](https://user-images.githubusercontent.com/27310921/151706454-77579581-77f1-405c-a9e2-7576ff18b072.png)

**Comment by mcastiello** [comment]
My best guess on this one is that by hovering over a different HTML element, the event intercepted by the context is not the one dispatched by the canvas. Actually I think that the fact that they use the same context may be the cause of the issue.
I need to investigate this one

**Comment by mcastiello** [comment]
New version is `1.3.24`

**Comment by Sylraka** [comment]
Now it works! Thank you.
