### ISSUE TITLE
miss tutorial or live-examples

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#5]
I want to learn how I can use pixi-reactive, but I don't know how I can start with. The code snippets don't run in my react and pixi-environment and there are not enough informations in the internet to debug the setup.

**Comment by mcastiello** [comment]
Hi Sylraka. I'd be happy to help.
As you can see in the README file, there's a link to an online documentation: https://mcastiello.github.io/pixi-reactive/
There are quite a few example, but if you need more help, feel free to ask :-)

**Comment by Sylraka** [comment]
Hey mcastiello,
I know the website, but the code snippets can't tell me how I can integrate the typescript file and the render function (for example: the function PixiCanvasExample from https://mcastiello.github.io/pixi-reactive/#/index/components/pixicanvas/) into another react component. 

**To the typescript integration:**
I found out that I need the devDependencies  "typescript" and "@types/react", but the code example (saved in a file named pixiTest.ts) still throw errors. 

The Tooltip from my IDE throws 
"Type '() => { 300: any; }' is not assignable to type 'FC<{}>'." in line 39 of the example, 
"'PixiCanvas' refers to a value, but is being used as a type here. Did you mean 'typeof PixiCanvas'?" in line 49 and "Unreachable code detected." in the other return-lines. 
I'm not sure if i integrated that example in the right way.

Can you tell me how I can integrate this?


**To the function call:**
For example, I want to call the PixiCanvasExample in the following component "board-global.js":


```
import Link from 'next/link'
import Head from 'next/head'
import Layout from '../../components/layout'

export default function BoardGlobal() {
    return (
        <Layout>
            <Head>
                <title>Board</title>
            </Head>
            <h1>Lorem ipsum</h1>
            <h2>
                <Link href="/">
                    <a>Back to home</a>
                </Link>
            </h2>
            <p>test</p>
        </Layout>
    )
}

```

Can you tell me how I can call the function or integrate the render elements?

**Comment by mcastiello** [comment]
You should feel free to convert it down to javascript, the library itself is compiled down to JS, plus all the types exported for those that want to use TS. Anyway, try to save your file like this:

```jsx
import React, { useReducer } from 'react';
import { PixiCanvas, PixiTilingSprite, PixiSprite } from 'pixi-reactive';

const textures = {
  galaxy: './static/assets/galaxy.png',
  stars: './static/assets/slow-stars.png',
  ship: './static/assets/spaceship.png'
};

/**
 * Update all the properties that will affect the scene using a React reducer.
 * @param {Space} state
 * @returns {Space}
 */
const updateScene = (state) => {
  let newDirection = state.direction;

  if ((state.direction && state.shipY <= 60) || (!state.direction && state.shipY >= 240)) {
    newDirection = !state.direction;
  }
  return {
    galaxyTileX: state.galaxyTileX - 0.1,
    starsTileX: state.starsTileX - 0.5,
    direction: newDirection,
    shipY: newDirection ? state.shipY - 0.5 : state.shipY + 0.5
  };
};

const PixiCanvasExample = () => {
  // Generate the scene state and the update function
  const [state, update] = useReducer(updateScene, {
    galaxyTileX: 0,
    starsTileX: 0,
    direction: false,
    shipY: 150
  });

  return (
    <PixiCanvas height={300} textures={textures} onUpdate={update}>
      <PixiTilingSprite texture={'galaxy'} tileX={state.galaxyTileX} />
      <PixiTilingSprite texture={'stars'} tileX={state.starsTileX} />
      <PixiSprite texture={'ship'} x={30} y={state.shipY} anchorY={0.5} />
    </PixiCanvas>
  );
};

export default PixiCanvasExample;
```

These are also the textures you'll need to make it work. You'll need to reference their path in the `textures` object.

![spaceship](https://user-images.githubusercontent.com/12670283/147263039-0c17196e-025d-4fa6-8e09-9390f3e5ba69.png)
![slow-stars](https://user-images.githubusercontent.com/12670283/147263076-6bf3a4fd-64e5-432c-b52c-ef91b4a71329.png)
![galaxy](https://user-images.githubusercontent.com/12670283/147263084-cd94b38f-331b-4d34-b069-7ff3d0e1c366.png)

Once you've done that, you can just import it like this:

```jsx
import Link from 'next/link'
import Head from 'next/head'
import Layout from '../../components/layout'
import PixiCanvasExample from '../../components/PixiCanvasExample'

export default function BoardGlobal() {
  return (
    <Layout>
      <Head>
        <title>Board</title>
      </Head>
      <h1>Lorem ipsum</h1>
      <h2>
        <Link href="/">
          <a>Back to home</a>
        </Link>
      </h2>
      <p>test</p>
      <PixiCanvasExample />
    </Layout>
  )
}
```

**Comment by Sylraka** [comment]
That works! I didn't know that it is so easy to downgrade typescript code into javascript.

One last question: which toolchain framework do you recommend?
From the list on https://reactjs.org/docs/create-a-new-react-app.html
I tried create-react-app and next.js. The first one forbids webpack adaptations (respectively adapt a port forwarding). Now i see that the pre-rendering from next.js is not compatible with your library, it throws the same error described in https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97 . 
Of course I could use one of the workarounds, but I think, there is a better toolchain framework for this use case? What do you use?

Thank you for your help, and Merry Christmas! :-)

**Comment by mcastiello** [comment]
I'm a fan of functional programming, downgrading classes may be a tad bit more complicated than this. But in most my example I'm quite sure it should not be complicated to convert them into plain JS.

I use either create-react-app or [craco](https://github.com/gsoft-inc/craco) (which simply extends the former but allows a little bit more customisations). When it comes to react libraries (like this one) I prefer microbundle, but it uses `rollup` instead of `webpack`.

Merry Christmas to you as well
