### ISSUE TITLE
miss explanation to the using of DOM-Elements

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#6]
The description of the package contains the following text:
"You will also be able to mix HTML content with PIXI objects... I mean, you may never need it, but it's there..."
but there are no explanation at any point how I can mix the HTML content with the PIXI objects.

**Comment by mcastiello** [comment]
Hi there, you can find almost all the examples you need on the online documentation.
You should be able to see the HTML content example [here](https://mcastiello.github.io/pixi-reactive/#/index/components/pixihtmlcontainer/).
Shout if you need more help :-)

**Comment by Sylraka** [comment]
Oh, you're right! 
Sorry, I should had to search a little bit better.

Maybe you can integrate a searchbar at your website? ;-)
