### ISSUE TITLE
react-router-dom throws MiniSignalBinding error when trying to route out of pixi-reactive-elements

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#7]
Hello mcastiello,

I tried to activate the routing in my craco and pixi-reactive setup and found out that the pages with pixi-elements throws errors when I try to navigate away from them (or between them). Then the following error is triggered:
![Screenshot 2022-01-08 at 16 26 55](https://user-images.githubusercontent.com/27310921/148650398-c2725eac-3e9f-458e-8169-cec563e2f769.png)

From all routes without pixi-elements the routing works fine. It seems like the error message comes from the Pixi-loader trying to detach some mini-signal-binding. Luckily the error can be clicked away and is not visible in production.
Do you have any idea how I can fix them?

My dependencies are:
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "web-vitals": "^2.1.0",
    "pixi.js": "^5.3.7",
    "pixi-reactive":"^1.3.10",
    "@craco/craco":"^6.4.3",
    "react-router-dom": "^6.2.1"

**Comment by mcastiello** [comment]
I think I've found the bug, I'll push an update as soon as I can.
the parameter required by `detach` is not the `callback` but the return value of the `add` method on the line above.

**Comment by mcastiello** [comment]
I've updated the code, new version is `1.3.11`. Give it a try and see if it happens again.
