### ISSUE TITLE
Mouse events cannot trigger because of missing collider-box (hitArea cannot used)

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#9]
Hello mcastiello,

I hope it is okey when I open the next issue. I'm not sure what I am doing wrong.

To make some element interactive I tried many ways out. I think (I hope) I am at the right way by setting a hitArea for a collider-box.
Unfortunately this box does not achieve the desired effect. I think I initialize it in the wrong way. Or is it a bug? 

Here is my code:

```
const BoardGlobalCanvas = () => {
    return (
        <PixiCanvas textures={textures}>
            <PixiTilingSprite texture={'tile'} tileScaleX={0.4} tileScaleY={0.4}/>
            <Ship/>
        </PixiCanvas>
    );
}

const Ship = () => {  
    const area = { x: 0, y: 0, width: 300, height: 300 };
   
    return(
        <PixiSprite texture={'ship'} alignY={0.5} alignX={0.5}
        cursor={CursorType.Help}
        hitArea={area}
        buttonMode={true} interactive={true} onClick={clicktest}/>
    );
}

const clicktest = () => {
    console.log("the function clicktest triggered!");
}
```

I also tried to define the Rectangle Element as a function, but that has also no effect:
```
const Ship = () => {  
    return(
        <PixiSprite texture={'ship'} alignY={0.5} alignX={0.5}
        cursor={CursorType.Help}
        hitArea={ColliderRectangle}
        buttonMode={true} interactive={true} onClick={clicktest}/>
    );
}

const ColliderRectangle = () => {
    return(
        <Rectangle x={0} y={0} width={200} height={200}/>
    );
}
```

And I tried the syntax from https://mcastiello.github.io/pixi-reactive/#/index/types/area/ , but that throws an "TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))" error, probably because I implement in javascript.
```
const Ship = () => {  
    const [area, setArea] = useState<Rectangle>({ x: 0, y: 0, width: 300, height: 300 });
    ...
```

What do I have to do to make an element clickable?

**Comment by mcastiello** [comment]
yep, looks like you found another bug.
New version update: `1.3.14`
By the way, the Rectangle is just a type, so the correct way of using it is your first example.

**Comment by mcastiello** [comment]
While I was there, I've also added an example of a click handler: https://mcastiello.github.io/pixi-reactive/#/index/components/pixisprite/

**Comment by Sylraka** [comment]
Now it works!
Thanks for the quick bugfixing.
It seems like i don't need an area to make an element interactive.

**Comment by mcastiello** [comment]
`hitArea` usually is needed when you want the "clickable" area of the display object to be different from its actual bounds (let's say you have a spaceship and you only want the cockpit to be clickable).
